/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@any-design/anyui')['Button']
    ACard: typeof import('@any-design/anyui')['Card']
    ADrawer: typeof import('@any-design/anyui')['Drawer']
    AFloat: typeof import('@any-design/anyui')['Float']
    AInput: typeof import('@any-design/anyui')['Input']
    APagination: typeof import('@any-design/anyui')['Pagination']
    ARadioButtonGroup: typeof import('@any-design/anyui')['RadioButtonGroup']
    ATag: typeof import('@any-design/anyui')['Tag']
    CharacterSelection: typeof import('./src/components/CharacterSelection.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatSide: typeof import('./src/components/ChatSide.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
